# Generated by Django 5.0.5 on 2024-05-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_pro', '0002_recipe_user_delete_receipe_recipe_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to='receipe_pro.user'),
        ),
    ]
