# Generated by Django 5.0.5 on 2024-05-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_pro', '0003_remove_recipe_recipe_image_alter_recipe_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
