# Generated by Django 5.0.5 on 2024-05-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_pro', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
