# Generated by Django 5.0.5 on 2024-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipe_pro', '0006_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_description', models.TextField()),
                ('recipe_detail_description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
