# Generated by Django 5.0.5 on 2024-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_pro', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
