# Generated by Django 5.0.6 on 2024-06-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_pro', '0011_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_user_name',
            field=models.CharField(default='recipe_user_name', max_length=100),
        ),
    ]
