# Generated by Django 5.0.6 on 2024-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe_pro', '0012_recipe_recipe_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_user_name',
            field=models.CharField(max_length=100),
        ),
    ]
