# Generated by Django 5.0.5 on 2024-05-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_mobile_no', models.BigIntegerField()),
                ('stu_dob', models.DateField()),
                ('stu_add', models.TextField()),
                ('stu_img', models.ImageField(upload_to='')),
                ('stu_file', models.FileField(upload_to='')),
            ],
        ),
    ]
