# Generated by Django 5.0.5 on 2024-05-11 13:01

from django.db import migrations

def delete_student_model(apps, schema_editor):
    Student = apps.get_model('home', 'Student')
    Student.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_student_model),
        migrations.DeleteModel('Student'),    
    ]





