# Generated by Django 5.0.5 on 2024-05-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240511_1831'),
    ]

    operations = [
    ]
